CREATE TABLE IF NOT EXISTS connections (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL,
  host VARCHAR(100) NOT NULL,
  port VARCHAR(10) NOT NULL,
  user VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  dbname VARCHAR(100) NOT NULL
);
